### ISSUE TITLE
Mega Man X2/X3 Error

### ISSUE THREAD

**Issue by OTFree** [StapleButter/blargSnes#20]
Hey, I just want to thank you all for your hard work! As a whole, blargSnes v.1.2 runs fantastic on my USA N3DSXL (running Homebrew via IronHax). However, when trying to run the US rom(s) of Mega Man X2/X3, the game reads: "Interface Register ERROR! Register File ERROR! Data Ram ERROR!"

I tried running Mega Man X, and it runs perfectly and doesn't have this issue. Guess it's a compatibility issue that'll get ironed out in the future? Thank you for your time.

**Comment by DiscostewSM** [comment]
blargSNES has no support for any enhancement chips, like Super FX (Star Fox, Yoshi's Island), DSP1 (Super Mario Kart, PilotWings), or even C4X (Megaman X2/X3).

At the moment, there are no plans to implement them. Maybe later, but right now, no.
